import '../globals.css'
import { CounterProvider } from './CounterProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <CounterProvider>{children}</CounterProvider>
      </body>
    </html>
  )
}
