import '../globals.css'
import { Inter } from 'next/font/google'
import { MapProvider } from '../../components/map/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MapProvider>{children}</MapProvider>
      </body>
    </html>
  )
}
